services:
  - type: web
    name: trade-feed-websocket-server
    env: node
    plan: free
    rootDir: websocket-server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production